force-app/main/default - Copy/objects/Debtor_Person__c/Debtor_Person__c.object-meta.xml
<CustomObject>
    <label>Debtor</label>
    <nameField>
        <label>Debtor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debtor Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default - Copy/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personel use</fullName>
                <label>Personel Use</label>
            </value>
            <value>
                <fullName>Enjoyment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
                <label>Personnel Loan</label>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Akshay education</fullName>
            </value>
            <value>
                <fullName>Mummy</fullName>
                <label>To Mom</label>
            </value>
            <value>
                <fullName>Home Loan EMI</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>New Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default - Copy/objects/Expense__c/fields/Debtor_Person__c.field-meta.xml
<CustomField>
    <fullName>Debtor_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debtor Person</label>
    <referenceTo>Debtor_Person__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default - Copy/objects/Expense__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default - Copy/objects/Expense__c/fields/Return_Status__c.field-meta.xml
<CustomField>
    <fullName>Return_Status__c</fullName>
    <label>Return Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Not yet</fullName>
                <default>true</default>
                <label>Not yet</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/expensesTriggerHandler.cls
public with sharing class expensesTriggerHandler {
    public static void checkifRecordTypeChanged(Map<Id,Expense__c> oldMap,Map<Id,Expense__c> newMap){
        for(Expense__c exp:newMap.values()){
            if(oldMap.get(exp.Id).RecordTypeId!=exp.RecordTypeId){
                if(exp.RecordTypeId=='0125i0000001uSjAAI'){
                    exp.Category__c='N/A';
                }
                else if(exp.RecordTypeId=='0125i0000001uSoAAI'){
                    exp.Return_Status__c='Self';
                }
            }
        }
    }
    public static void updateOutStandingAmount(List<Expense__c> newList,Map<Id,Expense__c> oldMap,Map<Id,Expense__c> newMap){
        Set<Id> debtorIds=new Set<Id>();
        Integer sum=0;
        List<Debtor_Person__c> updatedebtorpersons=new List<Debtor_Person__c>();
        if(oldMap==null  && newMap==null && newList!=null){
            for(Expense__c exp:newList){
                if(exp.RecordTypeId=='0125i0000001uSjAAI'){
                    if(exp.Debtor_Person__c!=null){
                        debtorIds.add(exp.Debtor_Person__c);
                    }
                }
            }
        }
        Map<Id,Debtor_Person__c> debtorpersons=new Map<Id,Debtor_Person__c>([select Id from Debtor_Person__c where Id in : debtorIds]);
        for(Expense__c exp:newList){
            if(exp.RecordTypeId=='0125i0000001uSjAAI'){
                if(!debtorpersons.isEmpty() && debtorpersons.containsKey(exp.Debtor_Person__c)){
                    Debtor_Person__c debt=debtorpersons.get(exp.Debtor_Person__c);
                    //sum=(Integer)debt.Outstanding_Amount__c;
                    //debt.Outstanding_Amount__c=sum+exp.Expense_Amount__c;
                    updatedebtorpersons.add(debt);
                }
            }
        }
        if(updatedebtorpersons.size()>0){
            update updatedebtorpersons;
        }
    }
}