force-app/main/default - Copy/objects/Expense__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Archive?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default - Copy/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personel use</fullName>
                <label>Personel Use</label>
            </value>
            <value>
                <fullName>Enjoyment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
                <label>Personnel Loan</label>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Akshay education</fullName>
            </value>
            <value>
                <fullName>Mummy</fullName>
                <label>To Mom</label>
            </value>
            <value>
                <fullName>Home Loan EMI</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>New Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default - Copy/objects/Expense__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default - Copy/objects/Expense__c/fields/Return_Status__c.field-meta.xml
<CustomField>
    <fullName>Return_Status__c</fullName>
    <label>Return Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Not yet</fullName>
                <default>true</default>
                <label>Not yet</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateAndSendCSVFileViaEmail.cls
public class CreateAndSendCSVFileViaEmail 
{
    public static void createAndSendCSVFile()
    {
        List<Expense__c> expenseList = new List<Expense__c>();
        expenseList = [Select Id, Name,Date__c,Expense_Amount__c,Return_Status__c,Category__c,RecordType.Name,Archive__c from Expense__c order by Date__c asc];

        //Separating field values using comma and storing in a list of string-'expenseDetails' 
        //The field values are displayed in different cells in CSV file when comma is encountered
        List<String> expenseDetails = new List<String>();
        if(expenseList != NULL && !expenseList.isEmpty())
        {
            for(Expense__c expObj: expenseList)
            {
                expenseDetails.add(expObj.RecordType.Name+ ',' +expObj.Date__c + ',' + expObj.Name + ',' + expObj.Expense_Amount__c+ ','+expObj.Return_Status__c+','+expObj.Category__c + ',' +expObj.Archive__c);
            }
        }
       
        //Creating CSV file
        String csvFile;
        String csvColumnHeader = 'Record Type,Date,Expense Name, Expense Amount,Return Status,Category,Archived\n';
        List<String> csvRowValues = new List<String>();
        
        //To add an attachment, Messaging.EmailFileAttachment class is used
        Messaging.EmailFileAttachment attach;
        if(expenseDetails != NULL && !expenseDetails.isEmpty())
        {
            csvFile = csvColumnHeader + String.join(expenseDetails,'\n');
            attach = new Messaging.EmailFileAttachment();
            attach.setContentType('text/csv');
            attach.setFileName('Expenses as on '+string.valueof(System.today())+'.csv');
            attach.setInline(true);
            attach.Body = Blob.valueOf(csvFile);
        }       
        
        //Creating recipient list
        List<String> recipientList = new List<String>();
        recipientList.add('chetankolakar@gmail.com');
        recipientList.add('chetankolakar123@gmail.com');
        //Sending email and attaching the CSV file
        List<Messaging.SingleEmailMessage> mailsList = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(recipientList);
        mail.setSubject('List of Expenses as on '+string.valueof(System.today()));
        String body = 'Refer below file for expenses as on '+string.valueof(System.today());
        mail.setHtmlBody(body);
        if(attach != NULL)
        {
            mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attach });//Set File Attachment
        }
        mailsList.add(mail);
        Messaging.SendEmailResult[] sendEmailResults = Messaging.sendEmail(mailsList);
    }
}