force-app/main/default - Copy/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personel use</fullName>
                <label>Personel Use</label>
            </value>
            <value>
                <fullName>Enjoyment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
                <label>Personnel Loan</label>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Akshay education</fullName>
            </value>
            <value>
                <fullName>Mummy</fullName>
                <label>To Mom</label>
            </value>
            <value>
                <fullName>Home Loan EMI</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>New Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default - Copy/objects/Expense__c/fields/Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expense_Amount__c</fullName>
    <label>Expense Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default - Copy/objects/Expense__c/fields/Return_Status__c.field-meta.xml
<CustomField>
    <fullName>Return_Status__c</fullName>
    <label>Return Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Not yet</fullName>
                <default>true</default>
                <label>Not yet</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WeeklyDataExportTest.cls
@isTest
public class WeeklyDataExportTest{
    public static String CRON_EXP = '14 0 0 25 7 ? 2022';
     public static testmethod void test1(){
      Test.startTest();
        Expense__c exp=new Expense__c();
        exp.Name='test1';
        exp.Date__c=Date.newInstance(2022, 07, 23);
        exp.Expense_Amount__c=100;
        exp.Category__c='Enjoyment';
        exp.Return_Status__c='Self';
        insert exp;

       // This test runs a scheduled job at midnight Sept. 3rd. 2022
        
       // Schedule the test job
       String jobId = System.schedule('WeeklyDataExportTest', CRON_EXP, new weekly_Data_export());
      // Get the information from the CronTrigger API object 
         CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
       // Verify the expressions are the same System.assertEquals(CRON_EXP, ct.CronExpression); 
      // Verify the job has not run 
      System.assertEquals(0, ct.TimesTriggered); 
      // Verify the next time the job will run 
      System.assertEquals('2022-07-26 14:00:00', String.valueOf(ct.NextFireTime));   
      Test.stopTest();        
     }
}